- name: show debug meesage
  debug: 
    msg: 
      - "{{ app }}"
      - "{{ ecr_endpoint }}"
      - "{{ work_directory }}"
      - "{{ docker_compose_yml_path }}"
      - "{{ database_url }}"
      - "{{ secret_key_base }}"

- name: Copy docker-compose.yml to remote
  copy:
    src: "{{ playbook_dir }}/../../docker-compose.yml"
    dest: "{{ work_directory }}"

- name: docker pull image
  shell: docker pull {{ ecr_endpoint }}

- name: docker tag image
  shell: docker tag {{ ecr_endpoint }} {{app}}:latest

- name: docker remove image
  shell: docker rmi {{ ecr_endpoint }}

- name: docker compose down
  shell: 
    cmd: docker-compose -p {{app}} down
    chdir: "{{ work_directory }}"

- name: docker compose up
  shell: 
    cmd: docker-compose -p {{app}} up -V -d 
    chdir: "{{ work_directory }}"
