- name: Copy docker-compose.yml to remote
  copy:
    src: "{{ depoly_directory }}/docker-compose.yml"
    dest: "{{ work_directory }}"

- name: Copy nginx conf to remote
  copy:
    src: "{{ depoly_directory }}/nginx"
    dest: "{{ work_directory }}"

- name: docker pull image
  shell: docker pull {{ ecr_endpoint }}

- name: docker tag image
  shell: docker tag {{ ecr_endpoint }} {{ app }}:latest

- name: docker remove image
  shell: docker rmi {{ ecr_endpoint }}

- name: docker compose down
  shell: 
    cmd: docker-compose -p {{ app }} down
    chdir: "{{ work_directory }}"

- name: docker compose up
  shell: 
    cmd: docker-compose -p {{ app }} up -V -d 
    chdir: "{{ work_directory }}"
