version: '3'

services:
  app:
    image: asia-yo
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - asia-yo
    depends_on:
      - redis

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - asia-yo
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - asia-yo

networks:
  asia-yo:
    external: true